name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 103.235.73.12
        username: jaja
        port: 2020
        password: nkeectud90HJGJ
        script: |
          cd /home/jaja/sites/stagingapi.eurekabookhouse.co.id/

          # Log into the server and check the current state of the repository
          git status

          # Fetch the latest changes from the 'main' branch
          git pull origin main

          # Add more deployment steps if needed

          # Log the result of the deployment
          echo "Deployment completed successfully."

# Add your secrets (SSH_PASSWORD) in the GitHub repository settings
