name: Deploy to Server

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Modify Permissions for sequelize-auto
      run: chmod +x ./node_modules/.bin/sequelize-auto

    - name: Resolve Git Merge Conflict
      run: git checkout --theirs .env
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 103.235.73.12
        username: jaja
        port: 2020
        password: nkeectud90HJGJ
        script: |
          cd /home/jaja/sites/stagingapi.eurekabookhouse.co.id/
          git checkout develop
          git pull origin develop
          npm run build && npm start
